package com.udacity.course3.reviews.ex;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(
    code = HttpStatus.NOT_FOUND, 
    reason = "Comment not found"
  )
public class CommentNotFoundException extends RuntimeException {

  
  /* constants */
  /** Serial version uid. Generated by eclise  */
  private static final long serialVersionUID = -6705220198556336044L;

  
  /* member variables */


  /* constructors */
  public CommentNotFoundException() {
    super();
  }
  
  public CommentNotFoundException(String msg) {
    super(msg);
  }

  
  /* methods */

}
